#! /usr/bin/env bash

usage="Usage: ./Combine-Html --input [input file] --output [output file]"

# parsing args
args=$(getopt -o "" --long "input:,output:" -n 'Combine-Html' -- "$@")

if [ $? -ne 0 ]; then
    echo $usage
    exit 1
fi

eval set -- "$args"
unset args

while true; do
    case "$1" in
        '--input')
            input=$2
            shift 2
            ;;
        '--output')
            output=$2
            shift 2
            ;;
        '--')
            shift
            break
            ;;
        *)
            echo $usage
            exit 1
            ;;
    esac
done

function readable() {
    if [[ -d "$1" || ! -f "$1" || ! -r "$1" ]]; then
        return 1
    else
        return 0
    fi
}

function writable() {
    # file exist
    if [[ -e "$1" && ! -w "$1" ]]; then
        return 1
    fi

    # file not exist
    if [[ ! -e "$1" && ! -w "$(dirname "$1")" ]]; then
        return 1 
    fi

    if [[ -d "$1" ]]; then
        return 1  
    fi
    return 0 
}


# main process function
function process() {
    local cur=$1
    local dir=$(dirname $cur)

    while IFS= read -r line; do
        after=$line
        while [[ $after =~ (.*)\<include\ src=\"([^\"]+)\"\ \/\>(.*) ]]; do 
            before=${BASH_REMATCH[1]}
            path=${BASH_REMATCH[2]}
            after=${BASH_REMATCH[3]}

            if [[ ${#before} -gt 0 ]]; then
                echo $before
            fi

            if [[ ${path:0:1} != '\/' && ${path:0:1} != '~' ]]; then
                path="${dir}/${path}"
            fi

            if ! readable "${path}"; then
                echo "<p style=\"color:red;\">Cannot access ${path}</p>"
            elif [[ ${path} == *.html ]]; then
                process $path
            elif [[ ${path} == *.png || ${path} == *.jpg ]]; then
                local image="$(cat ${curFile} | base64)"
                local extension="${path##*.}"
                echo "<img src=\"data:image/${extension};base64,${image}\" />"
            else
                cat $path
            fi 

            break 
        done

        if [[ ${#after} -gt 0 ]]; then
            echo $after
        fi     
    done < $cur
}

if ! readable ${input} || ! writable ${output} ; then
    echo $usage
    exit 1
fi

process $input > $output


