-- dnsdist configuration file, an example can be found in /usr/share/doc/dnsdist/examples/

setLocal("0.0.0.0:53")
newServer({address="127.0.0.1:10053", qps=20})
newServer({address="8.8.8.8", qps=20})
setServerPolicy(firstAvailable)

function filterLongTXT(dq)
	local packet = dq:getContent()
	local overlay = newDNSPacketOverlay(packet)
	local count = overlay:getRecordsCountInSection(DNSSection.Answer)

	if overlay.qtype == DNSQueryType.TXT then
		local totalLen = 0
		for idx=0, count-1 do
			local record = overlay:getRecord(idx)
			if record.type == DNSQueryType.TXT then
				totalLen = totalLen + record.contentLength
			end
		end

		if totalLen > 70 then
			return DNSResponseAction.Drop
		end
	end
	return DNSResponseAction.Allow
end

addResponseAction(AllRule(), LuaResponseAction(filterLongTXT))

addResponseAction(AllRule(), LuaResponseAction(filterLongTXT))

addAction(MaxQPSIPRule(20), DropAction())
addAction(RegexRule(".*\\.csdog\\.tw$"), DropAction())

addTLSLocal('0.0.0.0:853', '/etc/dnsdist/cert.pem', '/etc/dnsdist/key.pem')
