#! /usr/bin/env bash

usage="Usage: ./Combine-Html --input [input file] --output [output file]"

# parsing args
args=$(getopt -o "" --long "input:,output:" -n 'Combine-Html' -- "$@")

if [ $? -ne 0 ]; then
    echo $usage
    exit 1
fi

eval set -- "$args"
unset args

while true; do
    case "$1" in
        '--input')
            input=$2
            shift 2
            ;;
        '--output')
            output=$2
            shift 2
            ;;
        '--')
            shift
            break
            ;;
        *)
            echo $usage
            exit 1
            ;;
    esac
done

readable() {
    if [[ -d "$1" || ! -f "$1" || ! -r "$1" ]]; then
        return 1
    else
        return 0
    fi
}

writable() {
    # file exist
    if [[ -e "$1" && ! -w "$1" ]]; then
        return 1
    fi

    # file not exist
    if [[ ! -e "$1" && ! -w "$(dirname "$1")" ]]; then
        return 1 
    fi

    if [[ -d "$1" ]]; then
        return 1  
    fi
    return 0 
}


# main process function
process() {
    local cur=$1
    local dir=$(dirname $cur)

    while IFS= read -r line; do
        local after=$line

        while [[ $after =~ \<include\ src=\"([^\"]+)\"\ \/\> ]]; do
            local before="${after%%<include src=*}"
            local path=${BASH_REMATCH[1]}
            local after="${after#*<include src=\"${path}\" />}"

            if [[ ${#before} -gt 0 ]]; then
                printf "%s" "$before"
            fi

            local oripath="$path"
            if [[ ${path:0:1} != '\/' && ${path:0:1} != '~' ]]; then
                local path="${dir}/${path}"
            fi

            if ! readable "${path}"; then
                echo -n "<p style=\"color:red;\">Cannot access ${oripath}</p>"
            elif [[ ${path} == *.html ]]; then
                process "$path"
            elif [[ ${path} == *.png || ${path} == *.jpg ]]; then
                local image=$(base64 -w 0 "${path}")
                local extension="${path##*.}"
                printf "%s" "<img src=\"data:image/${extension};base64,${image}\" />"
            else
                printf "%s" "$(cat ${path})"
            fi 
        done

        if [[ ${#after} -gt 0 ]]; then
            printf "%s\n" "$after"
        else 
            printf "\n"
        fi     
    done < $cur
}

if ! readable ${input} || ! writable ${output} ; then
    echo $usage
    exit 1
fi

process $input > $output


